language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - pushd goon-gate.web
  - npm install
  - npm run build
  - npm test
  - popd

deploy:
  provider: script
  script: scripts/publish.sh
  on:
    branch: master
